import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProviders from "@/app/_providers/react-query.provider";
import Headers from "@/components/sharing/header";
import Footer from "@/components/sharing/footer";
import ToasterProvider from "./_providers/toast-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReactQueryProviders>
          <ToasterProvider />
          <Headers />
          {children}
          <div className="mt-5">
            <Footer />
          </div>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
